allowLocalFiles: true
options:
  looseYAML: false
  markdown:
    breaks: false
  html: true
  engine: marp-core
lang: ja-JP
inputDir: ./slides
output: ./slides
author: yuta-ushijima
theme: ./marp-themes/custom.css
footer: ©️ 2025 yuta ushijima
