allowLocalFiles: true
options:
  looseYAML: false
  markdown:
    breaks: false
  html: true
  engine: marp-core
pdf: true
lang: ja-JP
author: yuta-ushijima
css:
  - ./styles/custom.css
theme: uncover
footer: ©️ 2025 yuta ushijima
